---
title: "Graphs for final report"
author: "Torbjørn Skinnemoen Ottersen"
date: "2022-08-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(rvest)
library(MetBrewer)
```

```{r}
# Data reading =================================================================

## Function to read html file --------------------------------------------------
read_proff <- function(file, start, end) {
  # Specifying encoding to deal with occasional errors
  read_html(file, encoding = "UTF-8") |>
    html_node("#inner-frame") |>
    html_table() |>
    # removing empty column, using all_of(argument)
    select(
      REGNSKAPSPERIODE:all_of(start)
    ) |>
    # removing white space
    mutate(
      REGNSKAPSPERIODE = str_squish(REGNSKAPSPERIODE)
    ) |>
    # removing duplicate table sometimes created by read_html()
    filter(
      !row_number() > 176
    ) |>
    # removing duplicate rows
    filter(
      !grepl("Lukk", REGNSKAPSPERIODE)
    ) |>
    # tidying data using pivot_longer() and all_of(argument)
    pivot_longer(
      all_of(end):all_of(start),
      names_to = "year"
    ) |>
    mutate(
      # changing to real NAs
      value = na_if(value, "-"),
      # turning years into numbers
      year = as.integer(year),
      # creating a currency code column and turning current currency codes into
      # NAs
      valutakode = ifelse(REGNSKAPSPERIODE == "Valutakode", value, NA)
    ) |>
    # filling the currency column
    fill(
      valutakode,
      .direction = "updown"
    ) |>
    # removing dates and redundant currency
    filter(
      REGNSKAPSPERIODE != "Sluttdato" & REGNSKAPSPERIODE != "Startdato" &
        REGNSKAPSPERIODE != "Valutakode"
    ) |>
    mutate(
      # removing white space in numbers
      value = str_replace_all(value, "\\s", ""),
      # turning numbers into true numbers
      value = as.numeric(value),
      # removing values that are years
      value = ifelse(grepl("i hele 1000", REGNSKAPSPERIODE), NA, value)
    ) |>
    # removing any remaining duplicate rows
    distinct() |>
    # pivoting to create 'tidy' variables
    pivot_wider(
      names_from = REGNSKAPSPERIODE, values_from = value
    ) |>
    # tidying names
    clean_names() |>
    # removing headings from the table
    select(
      -lederlonn_i_hele_1000,
      -resultatregnskap_i_hele_1000,
      -balanseregnskap_i_hele_1000
    ) |>
    # making it clear what lonn refers to
    rename(
      lederlonn = lonn
    ) |>
    # Creating new variables for plots
    mutate(
      annual_profit = ifelse(arsresultat >= 0, TRUE, FALSE),
      balance_positive = ifelse(sum_egenkapital_og_gjeld >= 0, TRUE, FALSE)
    ) |>
    # arranging by year for practical display
    arrange(desc(year))
}

kreftforeningen <- read_proff("Data/Kreftforeningen.html", "2002", "2021")

care <- read_proff("Data/CARENorge2010_2021.html", "2010", "2021")
```


```{r}
## scale_fill_green ------------------------------------------------------------
# Function with slightly nicer colours than default; ensuring uniformity; +
# ensuring positive values are always green through a test for the presence of
# FALSE values
scale_fill_green <- function(variable) {
  scale_fill_met_d("Tsimshian",
    direction = ifelse(
      mean(variable,
        na.rm = TRUE
      ) == 1, -1, 1
    )
  )
}

```



```{r}
kreftforeningen |>
  rename(
    Year = year,
    `Net income` = arsresultat,
    `Net positive` = annual_profit
  ) |>
  ggplot(aes(Year, `Net income`, fill = `Net positive`)) +
  geom_col() +
  scale_y_continuous(labels = scales::label_dollar(prefix = "NOK ")) +
  scale_fill_green(kreftforeningen$annual_profit) +
  labs(
    x = "", y = "", title = "Net income (in thousands)"
  ) +
  theme_light() +
  theme(legend.position = "none")
```

```{r}
kreftforeningen |>
  rename(
    Year = year,
    `Total equity/liabilities` = sum_egenkapital_og_gjeld,
    `Positive equity` = balance_positive
  ) |>
  ggplot(aes(Year, `Total equity/liabilities`, fill = `Positive equity`)) +
  geom_col() +
  # using currency scale function to add correct currency code or ?
  scale_y_continuous(labels = scales::label_dollar(prefix = "NOK ")) +
  # using a function to ensure uniform colours irrespective of data
  scale_fill_green(kreftforeningen$balance_positive) +
  labs(
    x = "", y = "", title = "Total equity/liabilities (in thousands)"
  ) +
  theme_light() +
  theme(legend.position = "none")
```

```{r}
care |>
  rename(
    Year = year,
    `Total equity/liabilities` = sum_egenkapital_og_gjeld,
    `Positive equity` = balance_positive
  ) |>
  ggplot(aes(Year, `Total equity/liabilities`, fill = `Positive equity`)) +
  geom_col() +
  # using currency scale function to add correct currency code or ?
  scale_y_continuous(labels = scales::label_dollar(prefix = "NOK ")) +
  # using a function to ensure uniform colours irrespective of data
  scale_fill_green(kreftforeningen$balance_positive) +
  labs(
    x = "", y = "", title = "Total equity/liabilities (in thousands)"
  ) +
  theme_light() +
  theme(legend.position = "none")
```

```{r}
kreftforeningen |>
  # preparing for pivoting
  select(
    year, lederlonn, leder_annen_godtgjorelse
  ) |>
  # Compensation in ordinary numbers
  mutate(
    lederlonn = lederlonn * 1000,
    leder_annen_godtgjorelse = leder_annen_godtgjorelse * 1000
  ) |>
  # renaming for the purposes of the plot
  rename(
    Year = year,
    Salary = lederlonn,
    `Other compensation` = leder_annen_godtgjorelse
  ) |>
  # pivoting to join the two values to use fill
  pivot_longer(c(Salary, `Other compensation`), names_to = "Compensation") |>
  ggplot(aes(Year, value, fill = Compensation)) +
  geom_col() +
  # using currency scale function to add correct currency code or ?
  scale_y_continuous(labels = scales::label_dollar(prefix = "NOK ")) +
  # pretty colours
  scale_fill_met_d("Hokusai2", direction = -1) +
  labs(
    x = "", y = "", title = "CEO compensation"
  ) +
  theme_light() +
  theme(legend.position = "bottom")
```

```{r}
care |>
  rename(
    Year = year,
    `Net income` = arsresultat,
    `Net positive` = annual_profit
  ) |>
  ggplot(aes(Year, `Net income`, fill = `Net positive`)) +
  geom_col() +
  scale_y_continuous(labels = scales::label_dollar(prefix = "NOK ")) +
  scale_fill_green(kreftforeningen$annual_profit) +
  labs(
    x = "", y = "", title = "Net income (in thousands)"
  ) +
  theme_light() +
  theme(legend.position = "none")
```

