---
title: "Excel fun"
author: "Torbjørn Skinnemoen Ottersen"
date: '2022-07-11'
output: 
  html_document: 
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE}
library(readxl)
library(tidyverse)
library(janitor)
```

## Reading long file

```{r}
test <- read_excel("Data/OPXfinans test.xlsx")
test
```

## Tidying

```{r}
test2 <- test |> 
  mutate(
    category = ifelse(is.na(value), entry, NA) # transferring headings to category
  ) |> 
  fill(category) |> # filling category column
  fill(year) |> # filling year column
  filter(!is.na(value)) # removing headings
test2
```

### Removing rows containing 'sum' and 'total'
```{r}
test2_no_totals <- test2 |> 
  filter(
    !str_detect(entry, "^Sum") & !str_detect(entry, "^Total")
  )

test2_no_totals
test2_no_totals |>
  group_by(category) |> 
  summarise(
    sum = sum(value)
  )
```

## `pivot_wider()`
```{r}
test4 <- test2 |>
  unite(entry, c(category, entry), sep = " ") |> 
  select(-year) |> 
  pivot_wider(names_from = entry, values_from = value)

test4

test4 |> 
  summarise(
    sum = sum(`Revenue Private contributions`:`Revenue Other`)
  ) |> 
  summarise(
    test = sum == test4$`Revenue Sum total revenue`)
```

## Final version?
```{r}
excel <- read_excel("Data/OPXfinans2.xlsx")
excel <- clean_names(excel)

```

## Final final?
```{r}
excel <- read_excel("Data/OPXfinans_final.xlsx")
excel <- clean_names(excel)
excel_united <- excel |> 
  unite(entry, c(category, sub_category, name), sep = " ")
excel_united_wide <- excel_united |> 
  pivot_wider(names_from = entry, values_from = value)
excel_wide <- excel |> 
  pivot_wider(names_from = name, values_from = value) |> 
  arrange(desc(year))
excel_wide <- clean_names(excel_wide)

excel_united_wide <- clean_names(excel_united_wide)

excel_united_wide
united <- excel |> 
  unite(entry, c(category, name), sep = "_")
united <- clean_names(united)
united <- united |> 
  select(-sub_category)
united_wide <- united |> 
  pivot_wider(names_from = entry, values_from = value) |> 
  clean_names()
united_wide
united_wide |> 
  mutate(
    KPI = expenses_fundraising / revenue_private_contributions * 100
  ) |> 
  select(year, firm, KPI)

united_wide |> 
  mutate(
    KPI = (revenue_private_contributions - expenses_fundraising) / revenue_private_contributions * 100
  ) |> 
  select(year, firm, KPI)
```

