---
title: "PDF madness"
author: "Torbjørn Skinnemoen Ottersen"
date: '2022-07-08'
output: 
  html_document: 
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(tidyverse)
library(readtext)
library(pdftools)
library(readr)
```

## `readtext`, `pdf_text`

```{r}
# kreft <- readtext("Data/Kreftforeningen2021.pdf")
# kreft

krefttable <- pdf_text("Data/Krefttable2021.pdf")
summary(krefttable)
kreft_split <- str_split(krefttable, "\\n")
kreft_split <- trimws(kreft_split)
summary(kreft_split)
```

## Testing API

```{r}
library(httr)

getresponse <- GET("https://data.brreg.no/regnskapsregisteret/regnskap/951812528?%C3%A5r=2019&regnskapstype=SELSKAP")

getresponse

```

Doesn't seem to work.

## Testing Tabula

[Tabula](https://tabula.technology)

### One page

```{r}
tabula_kreft <- read_csv("Data/tabula-Krefttable2021.csv")
tabula_kreft
tabula_kreft_long <- tabula_kreft |> 
  pivot_longer(cols = `2021`:`2020`, names_to = "year")
tabula_kreft_long <- tabula_kreft_long |> 
  mutate(
    value = as.numeric(str_replace_all(value, "\\s", "")),
    year = as.integer(year)
  )

tabula_kreft_long <- tabula_kreft_long |> 
  arrange(desc(year))
tabula_kreft_long
```

### All pages
```{r}
tabula_kreft_full <- read_csv("Data/tabula-Krefttable2021-full.csv")
tabula_kreft_full_long <- tabula_kreft_full |> 
  pivot_longer(`2021`:`2020`, names_to = "year")
tabula_kreft_full_long
tabula_kreft_full_long <- tabula_kreft_full_long |> 
  mutate(
    value = as.numeric(str_replace_all(value, "\\s", "")),
    year = as.integer(year)
  )
tabula_kreft_full
tabula_kreft_full_long <- tabula_kreft_full_long |> 
  arrange(desc(year))
tabula_kreft_full_long |> 
  ggplot(aes(`ANSKAFFELSE AV MIDLER`, value, fill = as.factor(year))) +
  geom_col(position = "dodge2") +
  coord_flip()

tabula_kreft_full_long

tabula_kreft_full_long |> 
  filter(`ANSKAFFELSE AV MIDLER` %in% c("Medlemsinntekter", "Sum tilskudd",
                                        "Sum innsamlede midler og gaver",
                                        "Sum operasjonelle aktiviteter",
                                        "Finansinntekter")) |> 
  ggplot(aes(`ANSKAFFELSE AV MIDLER`, value, fill = as.factor(year))) +
  geom_col(position = "dodge2") +
  coord_flip()
```

## Brønnøysund pdf
```{r}
riksmaal <- pdf_text("Data/20220001922542-1.pdf")
riksmaal_split <- strsplit(riksmaal, "\\n")
riksmaal_split
```








