---
title: "Test parsing of Proff.no table (Kreftforeningen)"
author: "Torbjørn Skinnemoen Ottersen"
date: '2022-07-06'
output: 
  html_document: 
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

NOT a model to be followed...

```{r libraries}
library(tidyverse)
library(rvest)
```

### Reading in stages

```{r kreftforeningen}
# Reading saved html
table_kreft <- read_html("Links/Kreftforeningen.html") |> 
  html_node("#inner-frame") |> 
  html_table()

table_kreft

table_kreft2 <- table_kreft

# Removing white space
table_kreft2$REGNSKAPSPERIODE <- table_kreft$REGNSKAPSPERIODE |>
  str_squish()

# Removing empty column
table_kreft3 <- table_kreft2 |>
  select(REGNSKAPSPERIODE:`2002`)

# Removing duplicate rows
table_kreft4 <- table_kreft3 |>
  filter(!grepl("Lukk", REGNSKAPSPERIODE))

# tidying data:

table_kreft5 <- table_kreft4 |>
  pivot_longer(`2021`:`2002`, names_to = "year")

table_kreft6 <- table_kreft5

# Turning "-" into NA
table_kreft6 <- table_kreft6 |> 
  mutate(value = na_if(value, "-")) 

# Turning years into integers
table_kreft6$year <-as.integer(table_kreft6$year)

# Removing unnecessary dates
table_kreft7 <- table_kreft6 |> 
  filter(
    REGNSKAPSPERIODE != "Sluttdato" & REGNSKAPSPERIODE != "Startdato" &
      REGNSKAPSPERIODE != "Valutakode")

# Removing whitespace
table_kreft8 <- table_kreft7 |> 
  mutate(
    value = str_replace_all(value, "\\s", "")
  )

# Converting to numbers
table_kreft8 <- table_kreft8 |> 
  mutate(
    value = as.numeric(value)
  )

# Quick visualisation
table_kreft8 |> 
  filter(year == 2021) |> 
  ggplot(aes(REGNSKAPSPERIODE, value)) +
  geom_col() +
  coord_flip()

# Removing values that are years
table_kreft9 <- table_kreft8 |> 
  mutate(
    value = ifelse(grepl("i hele 1000", REGNSKAPSPERIODE), NA, value)
  )

# Viewing table
table_kreft9 |>
  arrange(desc(year))
```

>*Note that we might have to convert implicitly negative numbers.*

### Testing with different file

```{r opera}
# Reading saved html
opera <- read_html("Links/opera.html") |> 
  html_element("#inner-frame") |> 
  html_table(trim = TRUE)

# Removing white space
opera$REGNSKAPSPERIODE <- opera$REGNSKAPSPERIODE |>
  str_squish()

# Removing empty column
opera <- opera |>
  select(REGNSKAPSPERIODE:`1998`)

# Removing duplicate rows (hack)
opera <- opera |>
  filter(
  !row_number() > 176
)

# Removing duplicate rows
opera <- opera |>
  filter(!grepl("Lukk", REGNSKAPSPERIODE))

# tidying data:
opera <- opera |>
  pivot_longer(`2021`:`1998`, names_to = "year")

# Turning "-" into NA
opera <- opera |> 
  mutate(value = na_if(value, "-")) 

# Turning years into integers
opera$year <-as.integer(opera$year)

# Removing unnecessary dates
opera <- opera |> 
  filter(
    REGNSKAPSPERIODE != "Sluttdato" & REGNSKAPSPERIODE != "Startdato" &
      REGNSKAPSPERIODE != "Valutakode")

# Removing whitespace
opera <- opera |> 
  mutate(
    value = str_replace_all(value, "\\s", "")
  )

# Converting to numbers
opera <- opera |> 
  mutate(
    value = as.numeric(value)
  )

# Removing values that are years
opera <- opera |> 
  mutate(
    value = ifelse(grepl("i hele 1000", REGNSKAPSPERIODE), NA, value)
  )

# Viewing table
opera |>
  arrange(desc(year))

```

### As a single operation

```{r single operation}
opera_test <- read_html("Links/opera.html") |> 
  html_node("#inner-frame") |> 
  html_table() |> 
  select(
    REGNSKAPSPERIODE:`1998`) |> 
  mutate(
    REGNSKAPSPERIODE = str_squish(REGNSKAPSPERIODE)
  ) |> 
  filter(
  !row_number() > 176
  ) |> 
  filter(
    !grepl("Lukk", REGNSKAPSPERIODE)) |> 
  pivot_longer(
    `2021`:`1998`, names_to = "year") |> 
  mutate(
    value = na_if(value, "-"),
    year = as.integer(year)) |> 
  filter(
    REGNSKAPSPERIODE != "Sluttdato" & REGNSKAPSPERIODE != "Startdato" &
      REGNSKAPSPERIODE != "Valutakode") |> 
  mutate(
    value = str_replace_all(value, "\\s", "")
  ) |> 
  mutate(
    value = as.numeric(value)
  ) |> 
  mutate(
    value = ifelse(grepl("i hele 1000", REGNSKAPSPERIODE), NA, value)
  )

# Testing identity
identical(opera, opera_test)
```

### Function 1

```{r function}
# Function
read_proff <- function(file){
  read_html(file) |> 
  html_node("#inner-frame") |> 
  html_table() |> 
  select(
    REGNSKAPSPERIODE:`1998`) |> 
  mutate(
    REGNSKAPSPERIODE = str_squish(REGNSKAPSPERIODE)
  ) |> 
    filter(
      !row_number() > 176
    ) |>
  filter(
    !grepl("Lukk", REGNSKAPSPERIODE)
    ) |> 
  pivot_longer(
    `2021`:`1998`, names_to = "year") |> 
  mutate(
    value = na_if(value, "-"),
    year = as.integer(year)) |> 
  filter(
    REGNSKAPSPERIODE != "Sluttdato" & REGNSKAPSPERIODE != "Startdato" &
      REGNSKAPSPERIODE != "Valutakode") |> 
  mutate(
    value = str_replace_all(value, "\\s", "")
  ) |> 
  mutate(
    value = as.numeric(value)
  ) |> 
  mutate(
    value = ifelse(grepl("i hele 1000", REGNSKAPSPERIODE), NA, value)
  )
}

opera_func <- read_proff("Links/opera.html")

#Testing identity
identical(opera, opera_func)
```

### Slightly more robust function

- `file`: name and location of html file
- `start`: first available year as a string ("")
- `end`: last available year as a string ("")

```{r function_modified}
read_proff2 <- function(file, start, end){
  read_html(file, encoding = "UTF-8") |> 
  html_node("#inner-frame") |> 
  html_table() |> 
  select(
    REGNSKAPSPERIODE:start) |> 
  mutate(
    REGNSKAPSPERIODE = str_squish(REGNSKAPSPERIODE)
  ) |> 
    filter(
      !row_number() > 176
    ) |>
  filter(
    !grepl("Lukk", REGNSKAPSPERIODE)
    ) |> 
  pivot_longer(
    end:start, names_to = "year") |> 
  mutate(
    value = na_if(value, "-"),
    year = as.integer(year)) |> 
  filter(
    REGNSKAPSPERIODE != "Sluttdato" & REGNSKAPSPERIODE != "Startdato" &
      REGNSKAPSPERIODE != "Valutakode") |> 
  mutate(
    value = str_replace_all(value, "\\s", "")
  ) |> 
  mutate(
    value = as.numeric(value)
  ) |> 
  mutate(
    value = ifelse(grepl("i hele 1000", REGNSKAPSPERIODE), NA, value)
  )
}

read_proff2("Links/Kors.html", "2001", "2020") |> 
  arrange(desc(year))
```


