---
title: "XML annoyance"
author: "Torbjørn Skinnemoen Ottersen"
date: '2022-07-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(tidyverse)
library(xml2)
library(XML)
```

```{r}
x <- read_xml("Data/20191113105110-masse.xml")
xml_name(x)
xml_name(xml_parent(x))
x |> 
  xml_find_all("//*") |> 
  xml_path()
x1 <- xml_find_first(x, "//del")
x1
xml_name(xml_parent(x1))
xml_name(xml_children(x1))
xml_text(xml_find_first(x, "//hode"))

orgnr <- xml_text(xml_find_all(x, "//orgnr"))
xml_text(xml_find_first(x, "//info/feltkode"))
xml_text(xml_find_all(x, "//info/feltkode"))
xml_path(xml_find_all(x, "//info/feltkode"))




mass <- xmlParse("Data/20191113105110-masse.xml")

# xmlToDataFrame(mass, nodes = getNodeSet(mass, "//del"))

# Error in `[<-.data.frame`(`*tmp*`, i, names(nodes[[i]]), value = c(hode = "945011459S2018STORE14PLNRES2018010120181231MRNN201910059820190903BRLNJNNN", : 
# duplicate subscripts for columns

xmlToDataFrame(mass, nodes = getNodeSet(mass, "//del/hode"))
# works

# xmlToDataFrame(mass, nodes = getNodeSet(mass, "//del/info"))

# Error in `[<-.data.frame`(`*tmp*`, i, names(nodes[[i]]), value = c(feltkode = "7709", : 
# duplicate subscripts for columns

```

