---
title: "testing html sigh"
author: "Torbjørn Skinnemoen Ottersen"
date: "2022-07-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
read_proff_one <- function(file, start, end) {
  read_html(file, encoding = "UTF-8") |>
    html_node("#inner-frame") |> 
    html_table() |> 
    # removing empty column, using all_of(argument)
    select(
      REGNSKAPSPERIODE:all_of(start)
    ) |>
    # removing white space
    mutate(
      REGNSKAPSPERIODE = str_squish(REGNSKAPSPERIODE)
    ) |>
    # removing duplicate table sometimes created by read_html()
    filter(
      !row_number() > 176
    ) |>
    # removing duplicate rows
    filter(
      !grepl("Lukk", REGNSKAPSPERIODE)
    ) |>
    # tidying data using pivot_longer() and all_of(argument)
    pivot_longer(
      all_of(end):all_of(start),
      names_to = "year"
    ) |>
    # creating a currency code column and turning current currency codes into
    # NAs
    mutate(
      # changing to real NAs
      value = na_if(value, "-"),
      # turning years into numbers
      year = as.integer(year),
      # creating a currency code column and turning current currency codes into
      # NAs
      valutakode = ifelse(REGNSKAPSPERIODE == "Valutakode", value, NA)
    ) |>
    fill(
      valutakode,
      .direction = "downup"
    )
}

read_proff_two <- function(object) {
  object |>
    # removing dates and redundant currency
    select(-valutakode) |>
    filter(
      REGNSKAPSPERIODE != "Sluttdato" & REGNSKAPSPERIODE != "Startdato" &
        REGNSKAPSPERIODE != "Valutakode"
    ) |>
    mutate(
      # removing white space in numbers
      value = str_replace_all(value, "\\s", ""),
      # turning numbers into true numbers
      value = as.numeric(value),
      # removing values that are years
      value = ifelse(grepl("i hele 1000", REGNSKAPSPERIODE), NA, value)
    ) |>
    # removing any remaining duplicate rows
    distinct() |>
    # pivoting to create 'tidy' variables
    pivot_wider(
      names_from = REGNSKAPSPERIODE, values_from = value
    ) |>
    # tidying names
    clean_names() |>
    # removing headings from the table
    select(
      -lederlonn_i_hele_1000,
      -resultatregnskap_i_hele_1000,
      -balanseregnskap_i_hele_1000
    ) |>
    # making it clear what lonn refers to
    rename(
      lederlonn = lonn
    ) |>
    # Creating new variables for plots
    mutate(
      annual_profit = ifelse(arsresultat >= 0, TRUE, FALSE),
      balance_positive = ifelse(sum_egenkapital_og_gjeld >= 0, TRUE, FALSE)
    ) |>
    # arranging by year for practical display
    arrange(desc(year))
}
  ## Creating data frame from html file-----------------------------------------
html_currency <- 
    # Testing and creating data frame
    read_proff_one(
      "Old/Shiny/Test/Data/Kreftforeningen.html", "2002", "2021"
    )

htmldata <- read_proff_two(html_currency)

html_currency

htmldata |> 
  ggplot(aes(year, lederlonn)) +
  geom_col()


currency_scale <-
  scale_y_continuous(
    # Checking for uniform currency code
    labels = ifelse(length(unique(html_currency$valutakode)) == 1,
      # Using the currency code if uniform
      label_dollar(prefix = str_c(unique(html_currency$valutakode), " ")),
      # alternative prefix if multiple currencies in the data
      label_dollar(prefix = "? ")
    )
  )

scale_fill_green <- function(variable) {
  scale_fill_met_d("Tsimshian",
    direction = ifelse(
      mean(variable,
        na.rm = TRUE
      ) == 1, -1, 1
    )
  )
}

arsresultat_plot <-
    htmldata |>
      # renaming for plotly hover
      rename(
        Year = year,
        `Net income` = arsresultat,
        `Net positive` = annual_profit
      ) |>
      ggplot(aes(Year, `Net income`, fill = `Net positive`)) +
      geom_col() +
      # using currency scale function to add correct currency code or ?
      currency_scale +
      # using a function to ensure uniform colours irrespective of data
      scale_fill_green(htmldata$annual_profit) +
      labs(
        x = "", y = "", title = "Net income (in thousands)"
      ) +
      theme_light() +
      theme(legend.position = "none")
arsresultat_plot
```

