---
title: "Presentasjon OPX Fiffig tittel"
author: "Gruppe 5"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```

# Introduction

## <br> Introduction | OPX and their goal
- A startup developing solutions for socially responsible investment strategies
- The goal is to increase cash flow to charitable purposes 
- Donors' trust in NGOs' financial performance and their ability to deliver results is crucial for their choice of beneficients 

## <br> Introduction | How to assess financial performance?
- Data collection <br> OPX requested an automated solution to replace today's manual data collection
- Key Performance Indicators <br> OPX needed meaningful KPIs allowing to assess the relationship between assets and obligations 


## {data-background="Images/9-Brainstorming-techniques-to-come-up-with-great-ideas.png" data-background-size=cover}


## <br> Phase 1 – how to harvest and analyze the data?
- A webcrawler that could collect data across different websites? <br> This would be too difficult and it would only work with some organizations
- A code that could read PDF? <br> 


## <br> Phase 2 – Exploring three options
- Financial statements in yearly reports published as PDF <br>
Issue: Financial statements are not always published as text
- Webscraping financial statements from Proff.no <br>
Issue: Proff.no does not allow webscraping!
- Webscraping the Brønnøysund registry <br>
Issue: The registry does store downloadable XML documents, but the access cost about 500k kr

## <br> Workarounds... 
- Proff.no: It maaay be legal to manually download the websites as HTML instead of scraping 
- Brønnøysund: We attempted to request a temporary access to XML documents

## <br> ... and why they did not work
- Different accounting divisions at Proff.no and Brønnøysund prohibited extracting the correct sums the OPX wanted
- Not all NGOs publish their financial statements and certainly not for every year
- **Which led us to Phase 3 - scrapping the scraping**

# Data collection

# Data description

# Findings

# Limitations and steps forward